# Generated by Django 5.2.3 on 2025-06-16 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profiling_questions",
        ),
    ]
