# Generated by Django 5.2.3 on 2025-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_user_profiling_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="face_id",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
