# Generated by Django 5.2.3 on 2025-06-24 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontact',
            name='sendgrid_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='sendgrid_list_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CampaignStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('send_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sendgrid_campaign_id', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.emailcampaign')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
    ]
