# Generated by Django 5.2.3 on 2025-06-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_campaigncontact_sendgrid_contact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstep',
            name='sender_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
