# Generated by Django 5.2.3 on 2025-06-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_campaignstep_sender_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignstep',
            name='sender_id',
        ),
    ]
