# Generated by Django 5.2.3 on 2025-06-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_campaignstep_sender_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='emails_bounced',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='emails_delivered',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='emails_opened',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='emails_scheduled',
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
