# Generated by Django 5.2.3 on 2025-06-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_emailcampaign_emails_bounced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstep',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
