# Generated by Django 5.2.3 on 2025-06-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_campaignstep_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignstep',
            name='images',
        ),
    ]
