# Generated by Django 5.2.3 on 2025-06-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_campaignstep_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_steps/'),
        ),
    ]
