# Generated by Django 5.2.3 on 2025-06-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_campaignstep_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignstep',
            name='image',
        ),
    ]
