# Generated by Django 5.2.3 on 2025-06-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_campaignstep_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstep',
            name='image_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
