# Generated by Django 5.2.3 on 2025-06-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_campaignstep_image_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignstep',
            name='image_metadata',
        ),
    ]
