# Generated by Django 5.2.3 on 2025-07-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_campaignstepimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="address",
            new_name="district",
        ),
        migrations.AddField(
            model_name="user",
            name="user_selected_interests",
            field=models.ManyToManyField(
                blank=True, related_name="interested_users", to="core.interest"
            ),
        ),
    ]
