# Generated by Django 5.2.3 on 2025-07-01 05:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_rename_address_user_district_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_selected_interests",
        ),
    ]
