# Generated by Django 5.2.3 on 2025-07-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_user_user_selected_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='mallstore',
            name='store_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
