# Generated by Django 5.2.3 on 2025-07-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_mallstore_store_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mallstore',
            name='store_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
