# Generated by Django 5.2.3 on 2025-07-08 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_blueprint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blueprint",
            old_name="description",
            new_name="location",
        ),
    ]
