# Generated by Django 5.2.3 on 2025-07-08 03:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_rename_description_blueprint_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blueprint",
            old_name="location",
            new_name="description",
        ),
    ]
