# Generated by Django 5.2.3 on 2025-07-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_mallstore_store_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstep',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
