# Generated by Django 5.2.3 on 2025-07-09 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_rename_location_blueprint_description"),
        ("core", "0023_campaignstep_is_active"),
    ]

    operations = []
