# Generated by Django 5.2.3 on 2025-07-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_merge_20250709_0409"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprint",
            name="camera_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
