version: '3.8'

services:
  videoxpert-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: videoxpert-api
    ports:
      - "5183:5183"   # HTTP
    environment:
      - VIDEOXPERT_SERVER_IP=${VIDEOXPERT_SERVER_IP}
      - VIDEOXPERT_SERVER_PORT=${VIDEOXPERT_SERVER_PORT:-443}
      - VIDEOXPERT_USERNAME=${VIDEOXPERT_USERNAME}
      - VIDEOXPERT_PASSWORD=${VIDEOXPERT_PASSWORD}
      - VIDEOXPERT_LICENSE_KEY=${VIDEOXPERT_LICENSE_KEY}
      - VIDEOXPERT_USE_SSL=${VIDEOXPERT_USE_SSL:-true}
      - VIDEOXPERT_TIMEOUT_MINUTES=${VIDEOXPERT_TIMEOUT_MINUTES:-1000}
      - VIDEOXPERT_OUTPUT_DIRECTORY=./exports
    volumes:
      # Mount exports directory for persistent storage
      - videoxpert-exports:/app/exports
    networks:
      - videoxpert-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "powershell", "-Command", "try { Invoke-WebRequest -Uri http://localhost:5183/api/health -UseBasicParsing | Out-Null; exit 0 } catch { exit 1 }"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

networks:
  videoxpert-network:
    driver: bridge

volumes:
  videoxpert-exports:
    driver: local 