# Generated by Django 5.2.3 on 2025-06-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovementLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("track_id", models.IntegerField()),
                ("bbox", models.JSONField()),
                ("state", models.CharField(max_length=20)),
                ("store", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
