# Generated by Django 5.2.3 on 2025-07-18 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0002_dailyvideoexport"),
        ("logs", "0002_movementlog_camera_id_movementlog_confidence_and_more"),
    ]

    operations = []
