# Generated by Django 5.2.3 on 2025-07-18 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0003_merge_20250718_0739"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movementlog",
            name="camera_id",
        ),
        migrations.RemoveField(
            model_name="movementlog",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="movementlog",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="movementlog",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="movementlog",
            name="face_id",
        ),
    ]
