# Generated by Django 5.2.3 on 2025-07-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_remove_movementlog_camera_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementlog',
            name='track_id',
            field=models.IntegerField(),
        ),
    ]
